language: java
jdk:
- oraclejdk8
before_install:
#- openssl aes-256-cbc -K $encrypted_83a3be3a9e36_key -iv $encrypted_83a3be3a9e36_iv
#  -in application.properties.enc -out C:\\Users\\santi\\IdeaProjects\\lab2-big-ws\\src\\main\\resources\\application.properties
#  -d
- openssl aes-256-cbc -K -A $encrypted_83a3be3a9e36_key -iv $encrypted_83a3be3a9e36_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
#dd:
#- openssl aes-256-cbc -K $encrypted_83a3be3a9e36_key -iv $encrypted_83a3be3a9e36_iv
#  -in application.properties.enc -out C:\\Users\\santi\\IdeaProjects\\lab2-big-ws\\src\\main\\resources\\application.properties
#  -d
