language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_9e731eb1644e_key -iv $encrypted_9e731eb1644e_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties
  -d
